name: cicullis
description: >
  Deterministic CI gate enforcing irreversible decisions.

author: Midia Kiasat

runs:
  using: composite
  steps:
  - name: CICULLIS gate
    shell: bash
    run: |
      chmod +x "$GITHUB_ACTION_PATH/gate.sh"
      "$GITHUB_ACTION_PATH/gate.sh"
    - shell: bash
      run: |
        chmod +x gate.sh
        ./gate.sh

branding:
  icon: slash
  color: red

# reindex: 2026-02-23T11:23:53Z
