name: cicullis
description: >
  A GitHub Action that enforces irreversible contracts at CI time.
  Binary gate. Deterministic rules. Fails builds on boundary violations.

author: midiakiasat

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        chmod +x gate.sh
        ./gate.sh

branding:
  icon: slash
  color: red
