name: cicullis
description: "Deterministic CI gate enforcing irreversible decisions."
author: "Midia Kiasat"
branding:
  icon: shield
  color: gray-dark

inputs:
  mode:
    description: "pass|enforce"
    required: false
    default: "pass"

runs:
  using: "composite"
  steps:
    - name: CICULLIS gate
      shell: bash
      env:
        CICULLIS_MODE: ${{ inputs.mode }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/gate.sh"
        "$GITHUB_ACTION_PATH/gate.sh"
