name: cicullis
description: "Deterministic CI gate enforcing irreversible decisions."
author: "Midia Kiasat"
branding:
  icon: shield
  color: gray-dark

inputs:
  mode:
    description: "pass|enforce"
    required: false
    default: "pass"
  profile:
    description: "Path to policy profile file (required for enforce)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: CICULLIS gate
      shell: bash
      env:
        CICULLIS_MODE: ${{ inputs.mode }}
        CICULLIS_PROFILE: ${{ inputs.profile }}
      run: |
        bash "$GITHUB_ACTION_PATH/gate.sh"
